name: Upload to Storacha

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        type: string
      commit:
        required: true
        type: string
      supabaseKey:
        required: true
        type: string
      signedUrl:
        required: true
        type: string
      sig:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger server upload
      env:
        SERVER_URL: "https://your-ngrok-url/api/my-upload/storacha-upload"
        AUTH_TOKEN: ${{ secrets.STORACHA_TRIGGER_SECRET }}
      run: |
        echo "🔁 Calling server to pull from Supabase and upload to Storacha..."

        JSON=$(jq -n \
        --arg repo "${{ github.event.inputs.repository }}" \
        --arg commit "${{ github.event.inputs.commit }}" \
        --arg supa "${{ github.event.inputs.supabaseKey }}" \
        --arg url "${{ github.event.inputs.signedUrl }}" \
        --arg sig "${{ github.event.inputs.sig }}" \
        '{repo: $repo, commit: $commit, supabaseKey: $supa, signedUrl: $url, sig: $sig}')


        curl -X POST "$SERVER_URL" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AUTH_TOKEN" \
          -d "$JSON"
